export const MODEL_CONTROLTHROTTLE_DEFAULT = 1000;
export const MODEL_CONTROL_PLANES_DEFAULT = 1500;
export const MODEL_CONTROL_AUX_DEFAULT = 1000;
export const MODEL_MOTOR_DEFAULT_PWM = 980;
export const MODEL_SERVO_DEFAULT_PWM = 1500;